### ISSUE TITLE
Общекомандная статистика

### ISSUE THREAD

**Issue by desoo40** [desoo40/telegram#1]
Сделать расчет общекомандной статистики по запросу "статистика команда" с полями:

Total:

- Броски
- Броски в створ
- % бросков в створ
- % реализации бросков в створ
- Забитые
- Пропущенные
- ср. бросков за игру
- ср. бросков в створ за игру
- ср. голов за игру
- ср. пропущенных за игру
- % выигр. вбрасываний
- силовые
- заблокированные
- победы
- поражения
- ничьи
- сухие победы

**Comment by bsorokin** [comment]
готово

**Comment by desoo40** [comment]
готово?
